build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2

  - name: Generate a new file and commit to same repository
  run: python generate.py

  - name: check for changes
  run: git status

- name: stage changed files
  run: git add .

- name: commit changed files
  run: git commit -m "add random file"

- name: fetch from master
  run: git fetch origin master

- name: push code to master
  run: git push origin HEAD:main